'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.239
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.239.
'
Namespace wshumberto.wsorcamento
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="WSORCAMENTOSOAP", [Namespace]:="http://192.168.44.39:91/")>  _
    Partial Public Class WSORCAMENTO
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ALTERAROperationCompleted As System.Threading.SendOrPostCallback
        
        Private APROVAROperationCompleted As System.Threading.SendOrPostCallback
        
        Private CANCELAROperationCompleted As System.Threading.SendOrPostCallback
        
        Private GERAROperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Orcamento.My.MySettings.Default.Orcamento_wshumberto_wsorcamento_WSORCAMENTO
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ALTERARCompleted As ALTERARCompletedEventHandler
        
        '''<remarks/>
        Public Event APROVARCompleted As APROVARCompletedEventHandler
        
        '''<remarks/>
        Public Event CANCELARCompleted As CANCELARCompletedEventHandler
        
        '''<remarks/>
        Public Event GERARCompleted As GERARCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.44.39:91/ALTERAR", RequestNamespace:="http://192.168.44.39:91/", ResponseElementName:="ALTERARRESPONSE", ResponseNamespace:="http://192.168.44.39:91/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ALTERAR(ByVal TOKEN As TOKENSTRUCT, ByVal FICHAORCAMENTO As FICHAORCAMENTOSTRUCT) As <System.Xml.Serialization.XmlElementAttribute("ALTERARRESULT")> RETORNOSTRUCT
            Dim results() As Object = Me.Invoke("ALTERAR", New Object() {TOKEN, FICHAORCAMENTO})
            Return CType(results(0),RETORNOSTRUCT)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ALTERARAsync(ByVal TOKEN As TOKENSTRUCT, ByVal FICHAORCAMENTO As FICHAORCAMENTOSTRUCT)
            Me.ALTERARAsync(TOKEN, FICHAORCAMENTO, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ALTERARAsync(ByVal TOKEN As TOKENSTRUCT, ByVal FICHAORCAMENTO As FICHAORCAMENTOSTRUCT, ByVal userState As Object)
            If (Me.ALTERAROperationCompleted Is Nothing) Then
                Me.ALTERAROperationCompleted = AddressOf Me.OnALTERAROperationCompleted
            End If
            Me.InvokeAsync("ALTERAR", New Object() {TOKEN, FICHAORCAMENTO}, Me.ALTERAROperationCompleted, userState)
        End Sub
        
        Private Sub OnALTERAROperationCompleted(ByVal arg As Object)
            If (Not (Me.ALTERARCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ALTERARCompleted(Me, New ALTERARCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.44.39:91/APROVAR", RequestNamespace:="http://192.168.44.39:91/", ResponseElementName:="APROVARRESPONSE", ResponseNamespace:="http://192.168.44.39:91/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function APROVAR(ByVal TOKEN As TOKENSTRUCT, ByVal FICHAORCAMENTO As FICHAORCAMENTOSTRUCT) As <System.Xml.Serialization.XmlElementAttribute("APROVARRESULT")> RETORNOSTRUCT
            Dim results() As Object = Me.Invoke("APROVAR", New Object() {TOKEN, FICHAORCAMENTO})
            Return CType(results(0),RETORNOSTRUCT)
        End Function
        
        '''<remarks/>
        Public Overloads Sub APROVARAsync(ByVal TOKEN As TOKENSTRUCT, ByVal FICHAORCAMENTO As FICHAORCAMENTOSTRUCT)
            Me.APROVARAsync(TOKEN, FICHAORCAMENTO, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub APROVARAsync(ByVal TOKEN As TOKENSTRUCT, ByVal FICHAORCAMENTO As FICHAORCAMENTOSTRUCT, ByVal userState As Object)
            If (Me.APROVAROperationCompleted Is Nothing) Then
                Me.APROVAROperationCompleted = AddressOf Me.OnAPROVAROperationCompleted
            End If
            Me.InvokeAsync("APROVAR", New Object() {TOKEN, FICHAORCAMENTO}, Me.APROVAROperationCompleted, userState)
        End Sub
        
        Private Sub OnAPROVAROperationCompleted(ByVal arg As Object)
            If (Not (Me.APROVARCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent APROVARCompleted(Me, New APROVARCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.44.39:91/CANCELAR", RequestNamespace:="http://192.168.44.39:91/", ResponseElementName:="CANCELARRESPONSE", ResponseNamespace:="http://192.168.44.39:91/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CANCELAR(ByVal TOKEN As TOKENSTRUCT, ByVal NUMEROORCAMENTO As String) As <System.Xml.Serialization.XmlElementAttribute("CANCELARRESULT")> RETORNOSTRUCT
            Dim results() As Object = Me.Invoke("CANCELAR", New Object() {TOKEN, NUMEROORCAMENTO})
            Return CType(results(0),RETORNOSTRUCT)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CANCELARAsync(ByVal TOKEN As TOKENSTRUCT, ByVal NUMEROORCAMENTO As String)
            Me.CANCELARAsync(TOKEN, NUMEROORCAMENTO, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CANCELARAsync(ByVal TOKEN As TOKENSTRUCT, ByVal NUMEROORCAMENTO As String, ByVal userState As Object)
            If (Me.CANCELAROperationCompleted Is Nothing) Then
                Me.CANCELAROperationCompleted = AddressOf Me.OnCANCELAROperationCompleted
            End If
            Me.InvokeAsync("CANCELAR", New Object() {TOKEN, NUMEROORCAMENTO}, Me.CANCELAROperationCompleted, userState)
        End Sub
        
        Private Sub OnCANCELAROperationCompleted(ByVal arg As Object)
            If (Not (Me.CANCELARCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CANCELARCompleted(Me, New CANCELARCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.44.39:91/GERAR", RequestNamespace:="http://192.168.44.39:91/", ResponseElementName:="GERARRESPONSE", ResponseNamespace:="http://192.168.44.39:91/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GERAR(ByVal TOKEN As TOKENSTRUCT, ByVal FICHAORCAMENTO As FICHAORCAMENTOSTRUCT) As <System.Xml.Serialization.XmlElementAttribute("GERARRESULT")> RETORNOSTRUCT
            Dim results() As Object = Me.Invoke("GERAR", New Object() {TOKEN, FICHAORCAMENTO})
            Return CType(results(0),RETORNOSTRUCT)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GERARAsync(ByVal TOKEN As TOKENSTRUCT, ByVal FICHAORCAMENTO As FICHAORCAMENTOSTRUCT)
            Me.GERARAsync(TOKEN, FICHAORCAMENTO, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GERARAsync(ByVal TOKEN As TOKENSTRUCT, ByVal FICHAORCAMENTO As FICHAORCAMENTOSTRUCT, ByVal userState As Object)
            If (Me.GERAROperationCompleted Is Nothing) Then
                Me.GERAROperationCompleted = AddressOf Me.OnGERAROperationCompleted
            End If
            Me.InvokeAsync("GERAR", New Object() {TOKEN, FICHAORCAMENTO}, Me.GERAROperationCompleted, userState)
        End Sub
        
        Private Sub OnGERAROperationCompleted(ByVal arg As Object)
            If (Not (Me.GERARCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GERARCompleted(Me, New GERARCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://192.168.44.39:91/")>  _
    Partial Public Class TOKENSTRUCT
        
        Private cONTEUDOField As String
        
        Private eMPRESAFILIALField As EMPRESAFILIALSTRUCT
        
        Private mENSAGEMField As String
        
        Private mODULOField As String
        
        Private sENHAField As String
        
        Private sESSIONIDField As String
        
        '''<remarks/>
        Public Property CONTEUDO() As String
            Get
                Return Me.cONTEUDOField
            End Get
            Set
                Me.cONTEUDOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EMPRESAFILIAL() As EMPRESAFILIALSTRUCT
            Get
                Return Me.eMPRESAFILIALField
            End Get
            Set
                Me.eMPRESAFILIALField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MENSAGEM() As String
            Get
                Return Me.mENSAGEMField
            End Get
            Set
                Me.mENSAGEMField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MODULO() As String
            Get
                Return Me.mODULOField
            End Get
            Set
                Me.mODULOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SENHA() As String
            Get
                Return Me.sENHAField
            End Get
            Set
                Me.sENHAField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SESSIONID() As String
            Get
                Return Me.sESSIONIDField
            End Get
            Set
                Me.sESSIONIDField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://192.168.44.39:91/")>  _
    Partial Public Class EMPRESAFILIALSTRUCT
        
        Private eMPRESAField As String
        
        Private fILIALField As String
        
        '''<remarks/>
        Public Property EMPRESA() As String
            Get
                Return Me.eMPRESAField
            End Get
            Set
                Me.eMPRESAField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FILIAL() As String
            Get
                Return Me.fILIALField
            End Get
            Set
                Me.fILIALField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://192.168.44.39:91/")>  _
    Partial Public Class RETORNOSTRUCT
        
        Private cHAVEField As String
        
        Private cODIGOField As Single
        
        Private mENSAGEMField As String
        
        Private sUCESSOField As Boolean
        
        '''<remarks/>
        Public Property CHAVE() As String
            Get
                Return Me.cHAVEField
            End Get
            Set
                Me.cHAVEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CODIGO() As Single
            Get
                Return Me.cODIGOField
            End Get
            Set
                Me.cODIGOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MENSAGEM() As String
            Get
                Return Me.mENSAGEMField
            End Get
            Set
                Me.mENSAGEMField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SUCESSO() As Boolean
            Get
                Return Me.sUCESSOField
            End Get
            Set
                Me.sUCESSOField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://192.168.44.39:91/")>  _
    Partial Public Class ITEMORCAMENTOSTRUCT
        
        Private cODIGOPRODUTOField As String
        
        Private dESCRICAODETALHADAField As String
        
        Private pERCENTUALDESCONTOField As Single
        
        Private pRAZOENTREGAField As Single
        
        Private pRAZOGARANTIAField As Single
        
        Private pRECOLISTAField As Single
        
        Private pRECOVENDAField As Single
        
        Private qUANTIDADEField As Single
        
        Private vALORDESCONTOField As Single
        
        '''<remarks/>
        Public Property CODIGOPRODUTO() As String
            Get
                Return Me.cODIGOPRODUTOField
            End Get
            Set
                Me.cODIGOPRODUTOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DESCRICAODETALHADA() As String
            Get
                Return Me.dESCRICAODETALHADAField
            End Get
            Set
                Me.dESCRICAODETALHADAField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PERCENTUALDESCONTO() As Single
            Get
                Return Me.pERCENTUALDESCONTOField
            End Get
            Set
                Me.pERCENTUALDESCONTOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PRAZOENTREGA() As Single
            Get
                Return Me.pRAZOENTREGAField
            End Get
            Set
                Me.pRAZOENTREGAField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PRAZOGARANTIA() As Single
            Get
                Return Me.pRAZOGARANTIAField
            End Get
            Set
                Me.pRAZOGARANTIAField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PRECOLISTA() As Single
            Get
                Return Me.pRECOLISTAField
            End Get
            Set
                Me.pRECOLISTAField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PRECOVENDA() As Single
            Get
                Return Me.pRECOVENDAField
            End Get
            Set
                Me.pRECOVENDAField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property QUANTIDADE() As Single
            Get
                Return Me.qUANTIDADEField
            End Get
            Set
                Me.qUANTIDADEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property VALORDESCONTO() As Single
            Get
                Return Me.vALORDESCONTOField
            End Get
            Set
                Me.vALORDESCONTOField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://192.168.44.39:91/")>  _
    Partial Public Class FICHAORCAMENTOSTRUCT
        
        Private cODIGOCLIENTEField As String
        
        Private cONDICAOPAGAMENTOField As String
        
        Private cONTATOField As String
        
        Private dATASOLICITACAOField As Date
        
        Private dATAVALIDADEField As Date
        
        Private dETALHECONDICAOField As String
        
        Private eMISSAOField As Date
        
        Private eMISSAOFieldSpecified As Boolean
        
        Private fATURADOPORField As String
        
        Private iDUSUARIOField As String
        
        Private iTENSField() As ITEMORCAMENTOSTRUCT
        
        Private lOJACLIENTEField As String
        
        Private mOTIVOPRORROGACAOField As String
        
        Private nUMEROField As String
        
        Private oBSERVACAOField As String
        
        Private pOSSIBILIDADEVENDAField As String
        
        Private tIPOFRETEField As String
        
        Private tIPOORCAMENTOField As String
        
        Private tIPOSOLICITACAOField As String
        
        Private vALORFRETEField As Single
        
        '''<remarks/>
        Public Property CODIGOCLIENTE() As String
            Get
                Return Me.cODIGOCLIENTEField
            End Get
            Set
                Me.cODIGOCLIENTEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CONDICAOPAGAMENTO() As String
            Get
                Return Me.cONDICAOPAGAMENTOField
            End Get
            Set
                Me.cONDICAOPAGAMENTOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CONTATO() As String
            Get
                Return Me.cONTATOField
            End Get
            Set
                Me.cONTATOField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public Property DATASOLICITACAO() As Date
            Get
                Return Me.dATASOLICITACAOField
            End Get
            Set
                Me.dATASOLICITACAOField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public Property DATAVALIDADE() As Date
            Get
                Return Me.dATAVALIDADEField
            End Get
            Set
                Me.dATAVALIDADEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DETALHECONDICAO() As String
            Get
                Return Me.dETALHECONDICAOField
            End Get
            Set
                Me.dETALHECONDICAOField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public Property EMISSAO() As Date
            Get
                Return Me.eMISSAOField
            End Get
            Set
                Me.eMISSAOField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property EMISSAOSpecified() As Boolean
            Get
                Return Me.eMISSAOFieldSpecified
            End Get
            Set
                Me.eMISSAOFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FATURADOPOR() As String
            Get
                Return Me.fATURADOPORField
            End Get
            Set
                Me.fATURADOPORField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IDUSUARIO() As String
            Get
                Return Me.iDUSUARIOField
            End Get
            Set
                Me.iDUSUARIOField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property ITENS() As ITEMORCAMENTOSTRUCT()
            Get
                Return Me.iTENSField
            End Get
            Set
                Me.iTENSField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LOJACLIENTE() As String
            Get
                Return Me.lOJACLIENTEField
            End Get
            Set
                Me.lOJACLIENTEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MOTIVOPRORROGACAO() As String
            Get
                Return Me.mOTIVOPRORROGACAOField
            End Get
            Set
                Me.mOTIVOPRORROGACAOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NUMERO() As String
            Get
                Return Me.nUMEROField
            End Get
            Set
                Me.nUMEROField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OBSERVACAO() As String
            Get
                Return Me.oBSERVACAOField
            End Get
            Set
                Me.oBSERVACAOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property POSSIBILIDADEVENDA() As String
            Get
                Return Me.pOSSIBILIDADEVENDAField
            End Get
            Set
                Me.pOSSIBILIDADEVENDAField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TIPOFRETE() As String
            Get
                Return Me.tIPOFRETEField
            End Get
            Set
                Me.tIPOFRETEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TIPOORCAMENTO() As String
            Get
                Return Me.tIPOORCAMENTOField
            End Get
            Set
                Me.tIPOORCAMENTOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TIPOSOLICITACAO() As String
            Get
                Return Me.tIPOSOLICITACAOField
            End Get
            Set
                Me.tIPOSOLICITACAOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property VALORFRETE() As Single
            Get
                Return Me.vALORFRETEField
            End Get
            Set
                Me.vALORFRETEField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub ALTERARCompletedEventHandler(ByVal sender As Object, ByVal e As ALTERARCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ALTERARCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RETORNOSTRUCT
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RETORNOSTRUCT)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub APROVARCompletedEventHandler(ByVal sender As Object, ByVal e As APROVARCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class APROVARCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RETORNOSTRUCT
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RETORNOSTRUCT)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub CANCELARCompletedEventHandler(ByVal sender As Object, ByVal e As CANCELARCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CANCELARCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RETORNOSTRUCT
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RETORNOSTRUCT)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub GERARCompletedEventHandler(ByVal sender As Object, ByVal e As GERARCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GERARCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RETORNOSTRUCT
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RETORNOSTRUCT)
            End Get
        End Property
    End Class
End Namespace
